version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    versioning-strategy: auto
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'eslint*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'prettier*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
